import * as React from "react";
import Head from "next/head";
import styled from "styled-components";

import content from "../../list/found/all.json";

const Styled = styled.main`
	height: 100%;
	width: 100%;
	display: flex;
	align-items: center;
	justify-content: center;

	background-color: black;
	color: white;

	h1 {
		clip: rect(0 0 0 0);
		clip-path: inset(50%);
		height: 1px;
		overflow: hidden;
		position: absolute;
		white-space: nowrap;
		width: 1px;
	}

	a {
		font-size: 6rem;
		color: white;
	}
`;

export default function Home() {
	const [clickedTimes, setClickedTimes] = React.useState<number>(0);

	const generateURL = () =>
		`${url}/${content[Math.floor(Math.random() * content.length)]}`;
	const url = `https://find-and-update.company-information.service.gov.uk/company`;

	return (
		<>
			<Head>
				<title>Random Company</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Styled>
				<h1>Welcome to Random Company</h1>
				<a
					href={generateURL()}
					onClick={() => setClickedTimes(clickedTimes + 1)}
					target="_blank"
					rel="noopener noreferrer"
				>
					Go to random company page
				</a>
			</Styled>
		</>
	);
}
